#include "iafichas.h"

/* ============ MÓDULO 2: HISTORIA DA COMPUTACAO ============ */
const Ficha FICHAS_HIST[] = {
    /* --- raízes --- */
    {"historia da computacao", NULL, {"historia dos computadores"}, {"historia"},
     {{NULL,NULL}},
     "A aventura que vai da Maquina Analitica ao Linux - e que agora inclui a Existencia."},
    {"pioneiros", "historia da computacao", {NULL}, {"historia","pessoas"},
     {{NULL,NULL}},
     "Os gigantes sobre cujos ombros este projeto esta."},
    {"maquinas", "historia da computacao", {NULL}, {"historia","hardware"},
     {{NULL,NULL}},
     "Das valvulas ao transistor: o corpo fisico da computacao."},
    {"sistemas", "historia da computacao", {NULL}, {"historia","software"},
     {{NULL,NULL}},
     "Os sistemas operacionais que organizaram a maquina para as pessoas."},
    /* --- pioneiros --- */
    {"charles babbage", "pioneiros", {NULL}, {"historia","pessoas"},
     {{"criacao","Maquina Analitica (1837)"}},
     "Matematico ingles que projetou o primeiro 'computador' conceitual, no seculo XIX."},
    {"ada lovelace", "pioneiros", {"primeira programadora"}, {"historia","pessoas"},
     {{"feito","Primeiro algoritmo da historia (1843)"}},
     "Escreveu o primeiro algoritmo destinado a uma maquina, a de Babbage. Primeira programadora do mundo."},
    {"alan turing", "pioneiros", {"pai da computacao"}, {"historia","pessoas"},
     {{"modelo","Maquina de Turing (1936)"}},
     "Definiu o que e 'computavel'. Pai da computacao teorica e da inteligencia artificial como ideia."},
    {"grace hopper", "pioneiros", {"mariposa"}, {"historia","pessoas"},
     {{"curiosidade","O primeiro 'bug' real, em 1947"}},
     "Pioneira da programacao. Popularizou o termo 'debug' apos achar uma mariposa no computador."},
    {"dennis ritchie", "pioneiros", {"criador do c"}, {"historia","pessoas"},
     {{"criacao","Linguagem C (1972) e Unix"}},
     "Criou a linguagem C e co-criou o Unix. Sem ele, nao existiria este projeto."},
    {"ken thompson", "pioneiros", {"criador do unix"}, {"historia","pessoas"},
     {{"criacao","Unix e linguagem B"}},
     "Co-criador do Unix e da linguagem B, a mae do C."},
    {"linus torvalds", "pioneiros", {"criador do linux"}, {"historia","pessoas"},
     {{"criacao","Linux (1991) e Git"}},
     "Provou que codigo aberto pode mover o mundo. O proximo lar da Existencia."},
    /* --- máquinas --- */
    {"eniac", "maquinas", {NULL}, {"historia","hardware"},
     {{"ano","1945"}},
     "Primeiro computador eletronico de grande escala: 30 toneladas e 18 mil valvulas."},
    {"valvula", "maquinas", {NULL}, {"historia","hardware"},
     {{NULL,NULL}},
     "Amplificava sinais antes do transistor. Os primeiros computadores usavam milhares - e queimavam sem parar."},
    {"transistor", "maquinas", {NULL}, {"historia","hardware"},
     {{"ano","1947, Bell Labs"}},
     "Substituiu a valvula: menor, mais frio, mais confiavel. A celula da era digital."},
    /* --- sistemas --- */
    {"unix", "sistemas", {NULL}, {"historia","software"},
     {{"ano","1969, Bell Labs"}},
     "Pai do Linux, do BSD e da filosofia de sistema operacional que usamos ate hoje."},
    {"linux", "sistemas", {"gnu linux"}, {"historia","software","livre"},
     {{"ano","1991"}},
     "O maior projeto de software livre do mundo. Nascido de um estudante, mantido por milhares."},
    {"software livre", "sistemas", {"codigo aberto","open source"}, {"livre","filosofia"},
     {{"licenca","GPL"}},
     "Movimento que garante usar, estudar, modificar e compartilhar software. A bandeira deste projeto."},
    {"bug", "sistemas", {"erro de software"}, {"conceitos"},
     {{"origem","Mariposa real, 1947"}},
     "Erro em software. Todo programador conhece; poucos sabem que o primeiro foi um inseto de verdade."},
};
const int FICHAS_HIST_TAM = (int)(sizeof(FICHAS_HIST) / sizeof(FICHAS_HIST[0]));
