#include "iafichas.h"

/* ============ MÓDULO: PROGRAMACAO EM C ============
* Para crescer: acrescente fichas aqui (ou em novos módulos) — o motor não muda. */
const Ficha FICHAS_C[] = {
    {"linguagem c", NULL, {NULL}, {"historia","basico"},
     {{"criador","Dennis Ritchie, em 1972, no Bell Labs."}},
     "Criada em 1972 por Dennis Ritchie. Portatil, poderosa e a base de sistemas operacionais, embarcados e compiladores ate hoje."},
    {"memoria", NULL, {NULL}, {"memoria"},
     {{NULL,NULL}},
     "O subsistema mais importante do C: stack, heap, ponteiros e vazamentos. Quem domina memoria, domina o C."},
    {"ponteiro", "memoria", {"pointer","apontador"}, {"memoria","basico"},
     {{"sintaxe","int *p = &x;"},{"exemplo","*p = 10; // grava 10 na variavel x"}},
     "Variavel que guarda o endereco de outra variavel. O conceito mais poderoso (e temido) do C."},
    {"malloc", "memoria", {"alocacao dinamica"}, {"memoria","heap"},
     {{"sintaxe","void *p = malloc(n_bytes);"},{"exemplo","int *v = malloc(10 * sizeof(int));"},{"cuidado","Verifique NULL e sempre faca free depois."}},
     "Aloca memoria dinamica no heap em tempo de execucao."},
    {"free", "memoria", {"liberar"}, {"memoria","heap"},
     {{"sintaxe","free(p);"},{"cuidado","Usar p apos free causa use-after-free."}},
     "Devolve ao sistema a memoria alocada com malloc."},
    {"memory leak", "memoria", {"vazamento"}, {"memoria","bug"},
     {{"cuidado","Todo malloc precisa de um free no caminho certo."}},
     "Memoria alocada e nunca liberada: o programa engorda ate morrer."},
    {"stack", "memoria", {"pilha"}, {"memoria"},
     {{NULL,NULL}},
     "Memoria das variaveis locais e chamadas de funcao. Cresce e encolhe sozinha. Overflow aqui derruba o programa."},
    {"heap", "memoria", {NULL}, {"memoria"},
     {{NULL,NULL}},
     "Memoria dinamica gerenciada por malloc/free. Voce e o dono: aloca, libera e responde pelos erros."},
    {"buffer overflow", "seguranca", {"estouro de buffer"}, {"seguranca","bug"},
     {{"cuidado","Use strncpy, snprintf e tamanhos explicitos."}},
     "Escrever alem do fim de um buffer: a falha de seguranca classica do C."},
    {"struct", "tipos", {"estrutura"}, {"tipos","basico"},
     {{"sintaxe","struct Ponto { int x; int y; };"},{"exemplo","struct Ponto p = {10, 20};"}},
     "Agrupa variaveis de tipos diferentes sob um nome: o tijolo dos tipos complexos."},
    {"typedef", "tipos", {NULL}, {"tipos"},
     {{"sintaxe","typedef unsigned long u32;"}},
     "Cria um apelido para um tipo existente. Deixa o codigo legivel e portavel."},
    {"funcao", "funcoes", {NULL}, {"basico","funcoes"},
     {{"sintaxe","int soma(int a, int b) { return a + b; }"}},
     "Bloco nomeado e reutilizavel de codigo. A unidade de organizacao do C."},
    {"recursao", "funcoes", {"recursividade"}, {"funcoes","avancado"},
     {{"exemplo","int fat(int n){ return n<2?1:n*fat(n-1); }"},{"cuidado","Sem caso base, a pilha estoura."}},
     "Funcao que chama a si mesma. Elegante, mas cada chamada consome pilha."},
    {"ponteiros de funcao", "funcoes", {"function pointer"}, {"funcoes","avancado"},
     {{"exemplo","int (*op)(int,int) = &soma;"}},
     "Ponteiro que aponta para codigo: a base de callbacks, vtables e syscalls."},
    {"const", "boas praticas", {NULL}, {"boas praticas"},
     {{"exemplo","const int MAX = 32;"}},
     "Promessa de nao modificar. O compilador fiscaliza por voce."},
    {"static", "boas praticas", {NULL}, {"boas praticas"},
     {{NULL,NULL}},
     "Em variavel: sobrevive entre chamadas. Em funcao ou global: visivel so no arquivo."},
    {"volatile", "boas praticas", {NULL}, {"boas praticas","hardware"},
     {{NULL,NULL}},
     "Avisa o compilador: este valor muda fora do fluxo do codigo (hardware, ISR). Essencial em SO e embarcados."},
    {"include", "preprocessador", {"#include"}, {"preprocessador"},
     {{"sintaxe","#include \"meu.h\""}},
     "Copia o conteudo de um header no arquivo. Headers declaram, o .c implementa."},
    {"define", "preprocessador", {"macro","#define"}, {"preprocessador"},
     {{"sintaxe","#define TAM 64"}},
     "Macro de texto do preprocessador. Prefira const ou enum quando possivel."},
    {"compilador", "ferramentas", {"gcc"}, {"ferramentas"},
     {{"exemplo","gcc -O2 -c arquivo.c -o arquivo.o"}},
     "Traduz C para codigo de maquina. Recompile todo arquivo cujo header mudou."},
    {"objeto velho", "ferramentas", {"stale object"}, {"ferramentas","bug"},
     {{NULL,NULL}},
     "Arquivo .o nao recompilado apos mudar um header: layouts de struct divergem e causam bugs bizarrOS. Rebuild limpo resolve."},
    {"abi", "arquitetura", {"interface binaria"}, {"arquitetura"},
     {{NULL,NULL}},
     "Contrato binario estavel entre nucleo e aplicativos. Regra de ouro: adicionar nunca quebrar."},
    {"portabilidade", "arquitetura", {"codigo portavel"}, {"arquitetura"},
     {{NULL,NULL}},
     "Nucleo sem syscalls nem APIs de SO: o mesmo C roda em LBF OS, Linux, Windows ou bare metal."},
};
const int FICHAS_C_TAM = (int)(sizeof(FICHAS_C) / sizeof(FICHAS_C[0]));
